type: m

manager:
  address: ssmgr:4001
  password: '123456'

plugins:
  user:
    use: true
  account:
    use: true
  macAccount:
    use: true
  telegram:
    use: true
    token: ''

db:
  host: 'mysql'
  user: 'root'
  password: '123456'
  database: 'ssmgr'

redis:
  host: 'redis'
  port: 6379
  password: ''
  db: 0
