type: m

manager:
  address: ssmgr:4001
  password: '123456'

plugins:
  flowSaver:
    use: true
  user:
    use: true
  account:
    use: true
  macAccount:
    use: true
  group:
    use: true
  webgui:
    use: true
    host: '0.0.0.0'
    port: '80'
    site: 'http://127.0.0.1'

db:
  host: 'mysql'
  user: 'root'
  password: '123456'
  database: 'ssmgr'
